spring.application.name=Edupulse
server.port=7070

#DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/edupluse
spring.datasource.username=postgres
spring.datasource.password=qweasdzxc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.location=/tmp/uploads
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update